# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sEJ8Bw5qLM6h_0ltqdSqSD_AJzW4cHw_
"""

import random

class Player:
    def __init__(self):
        self.charge = 0
        self.died = False
        self.block = ""
        self.shoot = ""
        self.shooter = ["Gun", "Double Gun", "Headshot", "Bazooka", "RasenGun", "Double Bazooka"]
        self.blocker = ["Shield", "Double Shield", "Head Shield", "Barricade", "RasenGun Catcher", "Epic Barricade"]

    def set_charge(self, a_charge):
        self.charge = a_charge

    def set_died(self, a_died):
        self.died = a_died

    def set_shoot(self, num):
        self.shoot = self.shooter[num - 1]

    def get_shoot(self):
        return self.shoot

    def set_block(self, num):
        self.block = self.blocker[num - 1]

    def get_block(self):
        return self.block

    def get_charge(self):
        return self.charge

    def get_died(self):
        return self.died

def check_death(u_shoot, u_block, t_shoot, t_block, u_S, u_B, t_S, t_B, u_C, t_C):
    death = False

    if u_B and t_S:
        if u_block != t_shoot:
            death = True
    elif u_S and t_S:
        if u_shoot < t_shoot:
            death = True
    elif u_C and t_S:
        death = True

    return death

def main():
    player1 = Player()
    pc = Player()
    i = 1
    pc_charge = 0
    p1_charge = 0
    muchs = 0
    muchb = 0
    choices = 0
    choiceb = 0

    while not (player1.get_died() or pc.get_died()):
        logic = False
        pS = False
        pB = False
        cS = False
        cB = False
        cC = False
        pC = False

        if i == 1:
            print("Hi, apparently you don't know this game, so let me explain.")
            print("Each round you can either charge, shoot, or block.")
            print("If you charge, your amount of bullets +1 but you are vulnerable to any shots.")
            print("If you shoot and your opponent does not have the correct block/is charging/shoots you but with a less powerful weapon, you win and vice versa.")
            print("If you block the correct weapon, you are spared and your opponent loses that amount of bullets they have.")
            input("Press Enter to continue...")
            print("\nTurn 1!")
            print("Both of you charged.\n")
            p1_charge += 1
            pc_charge += 1
            player1.set_charge(p1_charge)
            pc.set_charge(pc_charge)
            input("Press Enter to continue...")
        else:
            while not logic:
                print(f"Player 1 charge: {p1_charge}")
                print(f"PC charge: {pc_charge}\n")
                choice = input("What would you do?\n"
                               "Shoot (S)\n"
                               "Block (B)\n"
                               "Recharge (R)\n")
                choice = choice.lower()

                if (p1_charge == 0 and choice in ['b', 'r']) or \
                   (p1_charge > 0 and choice in ['b', 'r', 's']):
                    logic = True
                else:
                    print("Invalid input!")
                    continue

                if choice == 's':
                    muchs = int(input("How much?\n"))
                    if 0 < muchs <= p1_charge <= 6:
                        player1.set_shoot(muchs)
                        p1_charge -= muchs
                        logic = True
                        pS = True
                        print(f"You pulled out a {player1.get_shoot()} and", end=" ")
                    else:
                        print("Invalid!")
                        continue
                elif choice == 'b':
                    muchb = int(input("How much?\n"))
                    player1.set_block(muchb)
                    pB = True
                    print(f"You blocked with a {player1.get_block()} and", end=" ")
                elif choice == 'r':
                    p1_charge += 1
                    pC = True
                    print("You charged and", end=" ")

                cpu = random.randint(0, 2)
                if pc_charge == 0:
                    cpu = 2

                if cpu == 0:
                    choices = random.randint(1, pc_charge)
                    pc.set_shoot(choices)
                    print(f"the CPU pulled out a {pc.get_shoot()}!")
                    cS = True
                    pc_charge -= choices
                elif cpu == 1:
                    choiceb = random.randint(1, pc_charge)
                    pc.set_block(choiceb)
                    cB = True
                    print(f"the CPU blocked with a {pc.get_block()}!")
                elif cpu == 2:
                    pc_charge += 1
                    cC = True
                    print("the CPU charged.")

            if check_death(muchs, muchb, choices, choiceb, pS, pB, cS, cB, pC, cC):
                player1.set_died(True)
            if check_death(choices, choiceb, muchs, muchb, cS, cB, pS, pB, cC, pC):
                pc.set_died(True)

            if player1.get_died():
                print("You died!")
                break
            elif pc.get_died():
                print("You won!")
                break

            input("Press Enter to continue...")
        i += 1


if __name__ == "__main__":
    main()
